apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
  - name: test-container
    image: nginx:alpine
 #   command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - secretRef:
        name: my-secret
    - configMapRef:
        name: ext-service-map
    env:
    - name: APP_NAME_VAR
      value: 'yessir'
    - name: SECRET1
      valueFrom:
        secretKeyRef:
          key: DB_NAME
          name: the-secret
    - name: CONFIGMAP1
      valueFrom:
        configMapKeyRef:
          key: api_endpoint
          name: ext-service-map
  volumes:
  - name: secret-volume
    secret:
      # Provide the name of the secret containing the files you want
      # to add to the container
      secretName: my-secret                     
  restartPolicy: Never
