# /opt/course/3/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: neb-new-job # add
spec:
  completions: 3 # add
  parallelism: 2 # add
  template:
    metadata:
      creationTimestamp: null
      labels: # add
        id: awesome-job # add
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep 2 && echo done
        image: busybox:1.31.0
        name: neb-new-job-container # update
        resources: {}
      restartPolicy: Never
status: {}
